# Generated by Django 5.1.3 on 2024-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('ano_foto', models.IntegerField()),
                ('data_postagem', models.DateTimeField()),
                ('url_foto', models.URLField(null=True)),
            ],
        ),
    ]
