# Generated by Django 5.1.3 on 2024-11-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
