# Generated by Django 5.1.3 on 2024-11-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFotos', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
