# Generated by Django 5.1.3 on 2024-11-17 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFotos', '0005_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
