# Generated by Django 5.1.3 on 2024-11-17 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFotos', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
